name: Build and Push Docker Image to Aliyun

# 触发条件：只有推送到主分支时触发
on:
  push:
    branches:
      - jl
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - '*.txt'
      - '**/*.txt'
      - '*.jpg'
      - '*.jpeg'
      - '*.png'
      - '*.gif'
      - '*.svg'
      - '*.ico'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.ico'
      - '.gitignore'
      - '.env.example'
      - '.vscode/**'
      - '.idea/**'
      - 'logs/**'
      - '*.log'
      - '**/*.log'
      - 'LICENSE'

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com  # 根据你的地域调整
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.cn-hangzhou.aliyuncs.com/ripper/new-api  # 替换为你的命名空间和仓库名
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64  # 支持多架构,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}